<?php
/*
	Plugin Version : Plugin for GuppY 4.5
	under CeCILL v2 Free Software Agreement
	Copyright (C) 2006-2007 by  HPSAM
	Web site = http://www.hpsam.info

	Translated by xiva (Valerie Pantzer) : http://pantzer.freehostia.coom/
	Adapté par Lud Bienaimé pour l'encodage en UTF-8 et le HTML5 
*/
if (stristr($_SERVER["SCRIPT_NAME"], "en-pvlang.inc")) {
  header("location:../index.php");
  die();
}
$pv_error1 = "Íåâîçìîæíî ïðîâåðèòü îáíîâëåíèå, ò.ê. allow_url_fopen îòêëþ÷åí.";
$pv_error2 = "Ïðîâåðêà îáíîâëåíèÿ íå óäàëàñü ïî íåèçâåñòíîé ïðè÷èíå.";
$pv_error3 = "Íåâîçìîæíî ïðîâåðèòü îáíîâëåíèå: íåïðàâèëüíûé Id.";
$pv_error4 = "Íåâîçìîæíî ïðîâåðèòü îáíîâëåíèå: Id íå îáíàðóæåí â áàçå äàííûõ.";
$pv_error5 = "Íåâîçìîæíî ïðîâåðèòü îáíîâëåíèå: îòêëþ÷åí Id.";
$pv_ok1 = "Äîñòóïíà íîâàÿ âåðñèÿ.";
$pv_ok2 = "âåðñèÿ ";
$pv_ok3 = " Äàòà ";
$pv_ok4 = "Ó âàñ óñòàíîâëåíà ñàìàÿ ïîñëåäíÿÿ âåðñèÿ.";
?>